apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 3
  template:
    metadata:
      name: apple
      labels:
        app: front-end
    spec:
      containers:
        - name: apple
          image: nginx
