apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      name: apple
      labels:
        app: apple
    spec:
      containers:
        - name: apple
          image: nginx
